[tool.poetry]
name = "movie-tut"
version = "0.1.0"
description = ""
authors = ["DrProfSgtMrJ"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
moviepy = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
